pipeline {
  agent any
    stages {
            stage('Git Progress') {
                 steps {
                        git branch: 'main',
                            url: 'https://github.com/f-lab-edu/half-time.git'
                        }

                 post {
                        success {
                                    sh 'echo "Successfully Cloned Repository"'
                                 }
                        failure {
                                    sh 'echo "Fail Cloned Repository"'
                                 }
                      }
            }

            stage('Build'){
                steps {
                // gradlew 있어야 함. git clone해서 프로젝트 가져옴
                sh 'chmod +x gradlew'
                sh './gradlew clean build'

                sh 'ls -al ./build/libs/*SNAPSHOT.jar'
                }

                post {
                    success {
                        echo 'gradle build success'
                    }

                    failure {
                        echo 'gradle build failed'
                    }
                }
            }

            stage('Test') {
                steps {
                    echo '테스트 관련된 몇 가지 단계를 수행한다.'
                }
            }

            stage('jar file to server'){
                steps{
                    sshagent(credentials:['Dev_server']){
                        sh 'ls -al ./build/libs/*SNAPSHOT.jar'
                        sh "scp -P 2222 -i .ssh/id_rsa.pem ./build/libs/*SNAPSHOT.jar root@106.10.38.91:/home/web-app/*SNAPSHOT.jar"
                    }
                }
            }

            stage('run server'){
                steps{
                    sshagent(credentials:['Dev_server']){
                        sh 'pwd'
                        sh './home/web-app/run.sh'
                    }
                }
            }
          }
       }
    }
}